# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'CometChatSample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CometChatSample
pod 'MessageSDKFramework' 
pod 'cometchat-ui' 
pod ‘Firebase/Auth’,'~> 4.8.2'
pod ‘Firebase/Database’,'~> 4.8.2'

end
